// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srvhvrkuqgacqvbqpvvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNydmh2cmt1cWdhY3F2YnFwdnZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMjAzNDQsImV4cCI6MjA1Nzc5NjM0NH0.pXnYGLR89PiVPfCTxQl0WfCqGteSlstmtgrKlL0wDK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);